TERM_PROGRAM=vscode
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000cbmh0032x4/T/
TERM_PROGRAM_VERSION=1.79.2
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
MallocNanoZone=0
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.QTSxMp4QcU/Listeners
__CF_USER_TEXT_ENCODING=0x18BA4:0x0:0x0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
LaunchInstanceID=52F772F2-A886-4795-BFC7-AE3E243FE04B
PWD=/Users/aasselma/minishell
LANG=en_US.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/aasselma
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LOGNAME=aasselma
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000cbmh0032x4/T/vscode-git-e4382e0f4d.sock
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
SECURITYSESSIONID=186a8
_=./minishell
